//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerRegs
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int c_id { get; set; }
        public string c_name { get; set; }
        public Nullable<int> c_age { get; set; }
        public string c_gender { get; set; }
    }
}
